import 'package:clipious/globals.dart';
import 'package:clipious/service.dart';
import 'package:clipious/settings/models/db/server.dart';
import 'package:clipious/settings/models/errors/invidious_service_error.dart';
import 'package:clipious/utils/sembast_sqflite_database.dart';
import 'package:clipious/videos/models/caption.dart';
import 'package:clipious/videos/models/video_transcript.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';

void main() {
  group('Invidious endpoint compatibility', () {
    test('keeps the current video and authenticated subscription endpoints',
        () {
      expect(urlGetVideo, '/api/v1/videos/:id');
      expect(urlGetUserFeed, '/api/v1/auth/feed');
      expect(urlGetSubscriptions, '/api/v1/auth/subscriptions');
      expect(urlGetTranscript, '/api/v1/transcripts/:id');
      expect(urlGetCaptions, '/api/v1/captions/:id');
    });
  });

  group('Service.handleResponse', () {
    final service = Service();

    test('reports an HTML reverse-proxy response before JSON decoding', () {
      final response = http.Response(
        '<a href="https://auth.example/login">Sign in</a>',
        302,
        headers: {'content-type': 'text/html; charset=utf-8'},
      );

      expect(
        () => service.handleResponse(response),
        throwsA(
          isA<InvidiousServiceError>().having(
            (error) => error.message,
            'message',
            'The reverse proxy returned HTML instead of Invidious JSON',
          ),
        ),
      );
    });

    test('reports a successful HTML proxy login page as a proxy error', () {
      final response = http.Response(
        '<!doctype html><title>Sign in</title>',
        200,
        headers: {'content-type': 'text/html; charset=utf-8'},
      );

      expect(
        () => service.handleResponse(response),
        throwsA(
          isA<InvidiousServiceError>()
              .having(
                (error) => error.message,
                'message',
                'The reverse proxy returned HTML instead of Invidious JSON',
              )
              .having(
                (error) => error.responseWasHtml,
                'responseWasHtml',
                isTrue,
              ),
        ),
      );
    });

    test('reports malformed JSON returned with a successful status', () {
      final response = http.Response(
        '{not-json',
        200,
        headers: {'content-type': 'application/json'},
      );

      expect(
        () => service.handleResponse(response),
        throwsA(
          isA<InvidiousServiceError>().having(
            (error) => error.message,
            'message',
            'The server returned malformed JSON',
          ),
        ),
      );
    });

    test('reports a non-JSON HTTP error with its status', () {
      final response = http.Response('Unavailable', 503);

      expect(
        () => service.handleResponse(response),
        throwsA(
          isA<InvidiousServiceError>().having(
            (error) => error.message,
            'message',
            'Request failed with HTTP 503',
          ),
        ),
      );
    });

    test('accepts an empty successful response', () {
      expect(service.handleResponse(http.Response('', 204)), isNull);
    });
  });

  group('Service.getTranscript', () {
    final caption = Caption(
      'English (auto-generated) & commentary',
      'en',
      '/api/v1/captions/video-id?label=English',
    );

    setUp(() async {
      db = await SembastSqfDb.createInMemory();
      const server = Server(
        url: 'https://inv.example',
        customHeaders: {'Authorization': 'Basic private-instance'},
      );
      await db.upsertServer(server);
      await db.useServer(server);
    });

    tearDown(() async {
      service = Service();
      await db.close();
    });

    test('returns the structured transcript without requesting captions',
        () async {
      final requests = <http.Request>[];
      final client = MockClient((request) async {
        requests.add(request);
        return http.Response(
          '''{"transcript":{"languageCode":"en","autoGenerated":true,"label":"English (auto-generated) & commentary","body":[{"type":"regular","startMs":0.0,"endMs":1500.0,"line":"Transcript text"}]}}''',
          200,
          headers: {'content-type': 'application/json'},
        );
      });

      final transcript =
          await Service(httpClient: client).getTranscript('video-id', caption);

      expect(requests, hasLength(1));
      expect(requests.single.url.path, '/api/v1/transcripts/video-id');
      expect(
        requests.single.url.queryParameters['label'],
        caption.label,
      );
      expect(
        requests.single.headers['Authorization'],
        'Basic private-instance',
      );
      expect(transcript, isA<VideoTranscript>());
      expect(transcript.lines.single.text, 'Transcript text');
    });

    test('falls back to WebVTT with the same label and custom headers',
        () async {
      final requests = <http.Request>[];
      final client = MockClient((request) async {
        requests.add(request);
        if (request.url.path.startsWith('/api/v1/transcripts/')) {
          return http.Response(
            '{"error":"Not found"}',
            404,
            headers: {'content-type': 'application/json'},
          );
        }
        return http.Response(
          'WEBVTT\n\n00:01.000 --> 00:02.000\nFallback text\n',
          200,
          headers: {'content-type': 'text/vtt; charset=utf-8'},
        );
      });

      final transcript =
          await Service(httpClient: client).getTranscript('video-id', caption);

      expect(requests, hasLength(2));
      expect(requests[0].url.path, '/api/v1/transcripts/video-id');
      expect(requests[1].url.path, '/api/v1/captions/video-id');
      for (final request in requests) {
        expect(request.url.queryParameters['label'], caption.label);
        expect(request.headers['Authorization'], 'Basic private-instance');
      }
      expect(transcript.lines.single.text, 'Fallback text');
    });

    test('throws an Invidious error when both instance requests fail',
        () async {
      final requests = <http.Request>[];
      final client = MockClient((request) async {
        requests.add(request);
        return http.Response('Unavailable', 503);
      });

      await expectLater(
        Service(httpClient: client).getTranscript('video-id', caption),
        throwsA(isA<InvidiousServiceError>()),
      );

      expect(requests, hasLength(2));
      expect(
        requests.every((request) => request.url.host == 'inv.example'),
        isTrue,
      );
    });
  });

  group('subscription writes', () {
    setUp(() async {
      db = await SembastSqfDb.createInMemory();
      const server = Server(
        url: 'https://inv.example',
        authToken: 'invidious-token',
      );
      await db.upsertServer(server);
      await db.useServer(server);
    });

    tearDown(() async {
      service = Service();
      await db.close();
    });

    test('does not silently convert a 403 subscribe response to false',
        () async {
      final client = MockClient((request) async => http.Response(
            '{"error":"Invalid token"}',
            403,
            headers: {'content-type': 'application/json'},
          ));
      final testService = Service(httpClient: client);

      await expectLater(
        testService.subscribe('UC123'),
        throwsA(isA<InvidiousServiceError>()),
      );
    });

    test('accepts a 204 unsubscribe response', () async {
      final client = MockClient((request) async => http.Response('', 204));
      final testService = Service(httpClient: client);

      expect(await testService.unSubscribe('UC123'), isTrue);
    });

    test('validates stored credentials with the subscriptions endpoint',
        () async {
      late http.Request captured;
      final client = MockClient((request) async {
        captured = request;
        return http.Response(
          '[]',
          200,
          headers: {'content-type': 'application/json'},
        );
      });
      final testService = Service(httpClient: client);

      expect(await testService.validateCurrentSession(), isTrue);
      expect(captured.url.path, '/api/v1/auth/subscriptions');
      expect(captured.headers['Authorization'], 'Bearer invidious-token');
    });

    test('clears stored credentials after an Invidious JSON 403', () async {
      final client = MockClient((request) async => http.Response(
            '{"error":"Invalid token"}',
            403,
            headers: {'content-type': 'application/json'},
          ));
      final testService = Service(httpClient: client);

      expect(await testService.validateCurrentSession(), isFalse);
      expect(db.getServer('https://inv.example')!.authToken, isNull);
    });

    test('keeps credentials when an outer proxy returns HTML', () async {
      final client = MockClient((request) async => http.Response(
            '<a href="https://auth.example/login">Sign in</a>',
            403,
            headers: {'content-type': 'text/html'},
          ));
      final testService = Service(httpClient: client);

      await expectLater(
        testService.validateCurrentSession(),
        throwsA(
          isA<InvidiousServiceError>().having(
            (error) => error.responseWasHtml,
            'responseWasHtml',
            isTrue,
          ),
        ),
      );
      expect(
        db.getServer('https://inv.example')!.authToken,
        'invidious-token',
      );
    });
  });
}
